Repository fabricadesoftware-ifc/FabricaPortal, pull requests merged in 2024-06, with the labels that each got.

#41 chore: add footer links
  src/components/FooterComp.vue
  src/data/mock/footer.ts
Labels: Estilização, Rotas

#49 feature: New background image
  public/img/fabricaAmbiente.jpeg
  src/assets/images/fabricaAmbiente.jpeg
Labels: Estilização

#48 refactor: Footer And Links
  src/components/FooterComp.vue
  src/data/mock/footer.ts
  src/data/mock/nav.ts
Labels: Estilização

#51 Refactor 44 filter style
  src/components/MembersView/FilterComp.vue
  src/data/mock/members.ts
  src/data/mock/projects.ts
Labels: Componente, Estilização

#56 FIX: Changing pic of hackathon championsho team (2022)
  public/img/Projects/FabricaPortal/FabricaDeSoftwarePortal.png
  public/img/Projects/FabricaPortal/hackathonTeam2022.png
  public/img/Projects/FabricaPortal/image1.png
  src/assets/images/Projects/FabricaPortal/image1.png
  src/data/mock/news.ts
Labels: Estilização

#57 Feature/fix responsive
  src/components/HomeView/NewsSection.vue
  src/components/HomeView/ProjectsSection.vue
  src/components/ProjectDetails/NewsCard.vue
  src/components/ProjectDetails/NewsProject.vue
  src/components/common/MemberCard.vue
  src/components/common/NewsCard.vue
  src/components/common/PaginationButtons.vue
  src/components/common/ProjectsCard.vue
  src/views/AboutUs.vue
  src/views/MembersView.vue
  src/views/NewsView.vue
  src/views/ProjectsView.vue
  src/views/PublicationDetails.vue
  src/views/PublicationsView.vue
Labels: Componente, Estilização

#58 Dev
  public/img/Projects/FabricaPortal/FabricaDeSoftwarePortal.png
  public/img/Projects/FabricaPortal/hackathonTeam2022.png
  public/img/Projects/FabricaPortal/image1.png
  src/assets/images/Projects/FabricaPortal/image1.png
  src/components/HomeView/NewsSection.vue
  src/components/HomeView/ProjectsSection.vue
  src/components/ProjectDetails/NewsCard.vue
  src/components/ProjectDetails/NewsProject.vue
  src/components/common/MemberCard.vue
  src/components/common/NewsCard.vue
  src/components/common/PaginationButtons.vue
  src/components/common/ProjectsCard.vue
  src/data/mock/news.ts
  src/views/AboutUs.vue
  src/views/MembersView.vue
  src/views/NewsView.vue
  src/views/ProjectsView.vue
  src/views/PublicationDetails.vue
  src/views/PublicationsView.vue
Labels: Componente, Estilização

#59 CHORE/members-update
  src/data/mock/members.ts
  src/data/mock/projects.ts
Labels: API, data

#60 Dev
  src/data/mock/members.ts
  src/data/mock/projects.ts
Labels: API, Estilização, data
